"""Initial migration.

Revision ID: 381302e95fc0
Revises: 7323de084dd3
Create Date: 2021-04-27 18:40:30.002039

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '381302e95fc0'
down_revision = '7323de084dd3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('photo', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('article', 'photo')
    # ### end Alembic commands ###
